# c++中的异常机制

```
#include <iostream>
using namespace std;

int divide(int x, int y)
{
    if(y == 0)
    {
        throw y; //抛出异常
    }
    return x/y;
}

void callDivide()
{
    divide(10, 0);
}

//c++的异常处理机制是跨函数的，异常必须处理。
int main() {
    try {
        divide(10,0);
    }catch (int){  //按照类型来捕获
        cout << "err" << endl;
    }

    try{
        callDivide();
    }catch (int e){
        cout << "除数为：" << e << endl; //当掉用的函数没有进行异常捕获的时候，会自动往上传递
    }

    return 0;
}
```
