# c++中的异常机制之栈解旋

```
#include <iostream>
using namespace std;

class Test{
public:
    Test(int a, int b)
    {
        this->a = a;
        this->b = b;
        cout << "Test(int, int)...." <<a<<", " <<b << endl;
    }
    ~Test() {
        cout << "a = " << a << ", b = " << b << ",  ~Test()..." << endl;
    }
private:
    int a;
    int b;
};

void divide(int x, int y) throw(int , char , char*)
{
    Test t1(1, 2);
    Test t2(10, 20);

    if (y == 0)
    {
        throw x;  //异常被抛出后，栈上的所有对象都会被自动析构，析构的顺序和构造的顺序相反。
    }

    cout << "x/y = " << x / y << endl;

    return;
}



int main() {
    Test t3(3, 3);
    try {
        divide(10,0);
    }catch (int){
        cout << "err" << endl;
    }


    return 0;
}
```
