# c++中的异常机制之实现自己的异常类

```
#include <iostream>
#include <string>
#include <exception>

using namespace std;

class MyException : public exception {
public:
    MyException(char *str) {
        this->m_s = str;
    }

    virtual const char *what() {
        cout << "MyException" << endl;
        return this->m_s;
    }

    ~MyException() {
        cout << "~MyException" << endl;
    }

private:
    char *m_s;
};

int main() {
    try {
        throw MyException("aaaa");
    }
    catch (MyException &e) {
        cout << e.what() << endl;
    }
}
```
